### ISSUE TITLE
arbitrum-sdk not supported `local` dev enviroment.

### ISSUE THREAD

**Issue by bradyjoestar** [OffchainLabs/arbitrum-sdk#176]
I startup a local enviroment on `ubuntu`, which the l1ChainId is `412346.`

and deposit Eth by `arbitrum-tutorial`, and it returns  the following error:

```
root@iZj6cf3sxrlbuuiwe8tsonZ:~/arbitrum-tutorials/packages/eth-deposit# yarn run depositETH
yarn run v1.22.19
$ hardhat run scripts/exec.js
Environmental variables properly set 👍
                            🔵🔵                            
                           🔵  🔵                           
                          🔵    🔵                          
                         🔵      🔵                         
                        🔵        🔵                        
                       🔵          🔵                       
                      🔵            🔵                      
                     🔵              🔵                     
                    🔵                🔵                    
                   🔵                  🔵                   
                  🔵                    🔵                  
                 🔵                      🔵                 
                🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵                
               🔵                          🔵               
              🔵                            🔵              
             🔵                              🔵             
            🔵                                🔵            
           🔵                                  🔵           
          🔵                                    🔵          
         🔵                                      🔵         
        🔵                                        🔵        
       🔵                                          🔵       
      🔵                                            🔵      
     🔵                                              🔵     
    🔵                                                🔵    
Arbitrum Demo: Deposit Eth via Arbitrum SDK
Lets
Go ➡️
...🚀

ArbSdkError: Unrecognized network 412346.
    at getNetwork (/root/arbitrum-tutorials/node_modules/@arbitrum/sdk-nitro/dist/lib/dataEntities/networks.js:223:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at isNitroL2 (/root/arbitrum-tutorials/node_modules/@arbitrum/sdk/dist/lib/utils/migration_types.js:192:23)
    at getL2Network (/root/arbitrum-tutorials/node_modules/@arbitrum/sdk/dist/lib/dataEntities/networks.js:64:9)
    at main (/root/arbitrum-tutorials/packages/eth-deposit/scripts/exec.js:36:21) {
  inner: undefined
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by gzeoneth** [comment]
You will need to call `addCustomNetwork` e.g.
```javascript
  addCustomNetwork({
    customL1Network: {
      "blockTime": 10,
      "chainID": 1337,
      "explorerUrl": "",
      "isCustom": true,
      "name": "EthLocal",
      "partnerChainIDs": [
        412346
      ],
      "rpcURL": "http://localhost:8545"
    },
    customL2Network: {
      "chainID": 412346,
      "confirmPeriodBlocks": 20,
      "ethBridge": {
        "bridge": "0x0ff69ab7483460783d905a684865cd75296be0e7",
        "inbox": "0xbc0784e484dfbf750f519cc983661d3bf1955746",
        "outbox": "0xf2C825Df2357f40222c0f6f1909D7bd9AD28513e",
        "rollup": "0x48683bf1640f060a86437d9da353c9a8c984258f",
        "sequencerInbox": "0x94e35a1009ab7acc359585fdb702fc7a7af2a70a"
      },
      "explorerUrl": "",
      "isArbitrum": true,
      "isCustom": true,
      "name": "ArbLocal",
      "partnerChainID": 1337,
      "rpcURL": "http://localhost:8547",
      "retryableLifetimeSeconds": 604800,
      "tokenBridge": {
        "l1CustomGateway": "0xDe67138B609Fbca38FcC2673Bbc5E33d26C5B584",
        "l1ERC20Gateway": "0x0Bdb0992B3872DF911260BfB60D72607eb22d5d4",
        "l1GatewayRouter": "0x4535771b8D5C43100f126EdACfEc7eb60d391312",
        "l1MultiCall": "0x36BeF5fD671f2aA8686023dE4797A7dae3082D5F",
        "l1ProxyAdmin": "0xF7818cd5f5Dc379965fD1C66b36C0C4D788E7cDB",
        "l1Weth": "0x24067223381F042fF36fb87818196dB4D2C56E9B",
        "l1WethGateway": "0xBa3d12E370a4b592AAF0CA1EF09971D196c27aAd",
        "l2CustomGateway": "0xF0B003F9247f2DC0e874710eD55e55f8C63B14a3",
        "l2ERC20Gateway": "0x78a6dC8D17027992230c112432E42EC3d6838d74",
        "l2GatewayRouter": "0x7b650845242a96595f3a9766D4e8e5ab0887936A",
        "l2Multicall": "0x9b890cA9dE3D317b165afA7DFb8C65f2e4c95C20",
        "l2ProxyAdmin": "0x7F85fB7f42A0c0D40431cc0f7DFDf88be6495e67",
        "l2Weth": "0x36BeF5fD671f2aA8686023dE4797A7dae3082D5F",
        "l2WethGateway": "0x2E76efCC2518CB801E5340d5f140B1c1911b4F4B"
      }
    }
  })
```

Assuming you are running `./test-node.bash` in nitro repo to setup the local environment, you will need to clone the sdk repo and run `yarn gen:network` (with .env configured to your local rpc) to deploy the token bridge and replace your deployment in the above format.

**Comment by bradyjoestar** [comment]
> ```js
> l1ERC20Gateway
> ```

appreciate for your help!
