### ISSUE TITLE
yarn gen:network not worked smootly for `ubuntu`

### ISSUE THREAD

**Issue by bradyjoestar** [OffchainLabs/arbitrum-sdk#188]
On my ubuntu machine, I startup  a local enviroment.
I used `yarn gen:network` to generate localNetwork.json, whick reported: 
```
Error: No such container: nitro_sequencer_1
Error: Command failed: docker exec nitro_sequencer_1 cat /config/deployment.json
Error: No such container: nitro_sequencer_1

    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at getCustomNetworks (/root/arbitrum-sdk/scripts/testSetup.ts:65:34)
    at setupNetworks (/root/arbitrum-sdk/scripts/testSetup.ts:131:74)
    at main (/root/arbitrum-sdk/scripts/genNetwork.ts:12:55)
    at Object.<anonymous> (/root/arbitrum-sdk/scripts/genNetwork.ts:26:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (/root/arbitrum-sdk/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 45 72 72 6f 72 3a 20 4e 6f 20 73 75 63 68 20 63 6f 6e 74 61 69 6e 65 72 3a 20 6e 69 74 72 6f 5f 73 65 71 75 65 6e 63 65 72 5f 31 0a>
  ],
  pid: 41792,
  stdout: <Buffer >,
  stderr: <Buffer 45 72 72 6f 72 3a 20 4e 6f 20 73 75 63 68 20 63 6f 6e 74 61 69 6e 65 72 3a 20 6e 69 74 72 6f 5f 73 65 71 75 65 6e 63 65 72 5f 31 0a>
}
Done in 10.15s.
```

It looks like the `nitro_sequencer_1` is called `nitro-sequencer-1` on ubuntu.

**Comment by fredlacs** [comment]
fixed in https://github.com/OffchainLabs/arbitrum-sdk/pull/197
