### ISSUE TITLE
I got an error calling yarn gen:network

### ISSUE THREAD

**Issue by songjianyang** [OffchainLabs/arbitrum-sdk#208]
```
yarn run v1.22.19
$ ts-node ./scripts/genNetwork.ts
123
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="confirmPeriodBlocks()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.3)
    at Logger.makeError (/home/test/arbitrum-tutorials/arbitrum-sdk/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/home/test/arbitrum-tutorials/arbitrum-sdk/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at Interface.decodeFunctionResult (/home/test/arbitrum-tutorials/arbitrum-sdk/node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
    at Contract.<anonymous> (/home/test/arbitrum-tutorials/arbitrum-sdk/node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
    at step (/home/test/arbitrum-tutorials/arbitrum-sdk/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/test/arbitrum-tutorials/arbitrum-sdk/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/home/test/arbitrum-tutorials/arbitrum-sdk/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'confirmPeriodBlocks()',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x91c9ca402976984c99ebd2b43826123442c592b8',
  args: [],
  transaction: {
    data: '0x2e7acfa6',
    to: '0x91c9Ca402976984C99eBD2B43826123442c592B8'
  }
}
Done in 23.25s.
```

**Comment by songjianyang** [comment]
My .env file:

```
ARB_URL="http://localhost:8547"
ETH_URL="http://localhost:8545"
ARB_KEY="e887f7d17d07cc7b8004053fb8826f6657084e88904bb61590e498caXXXXXXX"
ETH_KEY="e887f7d17d07cc7b8004053fb8826f6657084e88904bb61590e498caXXXXXXX"

```

**Comment by songjianyang** [comment]
@gzeoneth

**Comment by gzeoneth** [comment]
Which branch are you using? Try `c-nitro-next`
I am also working on a PR that let you deploy token bridge with the nitro test node https://github.com/OffchainLabs/nitro/pull/1189
