### ISSUE TITLE
`No retryable data found in error` in erc20 deposit

### ISSUE THREAD

**Issue by ikautak** [OffchainLabs/arbitrum-sdk#361]
I tried erc20 deposit using arbitrum/sdk@3.1.12, but the following error occurs
```
/home/shio/src/deposit/node_modules/@ethersproject/logger/src.ts/index.ts:269
        const error: any = new Error(message);
                           ^
Error: unsupported fragment (argument="value", value="error RetryableData (address from, address to, uint256 l2CallValue, uint256 deposit, uint256 maxSubmissionCost, address excessFeeRefundAddress, address callValueRefundAddress, uint256 gasLimit, uint256 maxFeePerGas, bytes data)", code=INVALID_ARGUMENT, version=abi/5.1.0)
    at Logger.makeError (/home/shio/src/deposit/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/shio/src/deposit/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.throwArgumentError (/home/shio/src/deposit/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
    at Function.Fragment.fromString (/home/shio/src/deposit/node_modules/@ethersproject/abi/src.ts/fragments.ts:471:23)
    at Function.Fragment.from (/home/shio/src/deposit/node_modules/@ethersproject/abi/src.ts/fragments.ts:432:29)
    at /home/shio/src/deposit/node_modules/@ethersproject/abi/src.ts/interface.ts:90:29
    at Array.map (<anonymous>)
    at new Interface (/home/shio/src/deposit/node_modules/@ethersproject/abi/src.ts/interface.ts:89:47)
    at Object.<anonymous> (/home/shio/src/deposit/node_modules/@arbitrum/sdk/dist/lib/dataEntities/retryableData.js:8:24)
    at Module._compile (node:internal/modules/cjs/loader:1256:14) {
  reason: 'unsupported fragment',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: 'error RetryableData (address from, address to, uint256 l2CallValue, uint256 deposit, uint256 maxSubmissionCost, address excessFeeRefundAddress, address callValueRefundAddress, uint256 gasLimit, uint256 maxFeePerGas, bytes data)'
```

node: v18.18.0
arbitrum/sdk: 3.1.12
ethers: ~~5.1.0~~ 5.6.0
source:
```js
import { Erc20Bridger, getL2Network } from "@arbitrum/sdk";
import { BigNumber, providers } from "ethers";

const main = async (): Promise<void> => {
    const l1Provider = new providers.JsonRpcProvider('https://ethereum-goerli.publicnode.com');
    const l2Provider = new providers.JsonRpcProvider('https://goerli-rollup.arbitrum.io/rpc');
    const fromAddress = '0xaA64a97583DB7393b15164F482627Ed43f553969';
    const usdcAddress = '0xD87Ba7A50B2E7E660f678A895E4B72E7CB4CCd9C';

    const l2Network = await getL2Network(l2Provider);
    const erc20Bridger = new Erc20Bridger(l2Network);
    const deposit = await erc20Bridger.getDepositRequest({
        l1Provider,
        l2Provider,
        from: fromAddress,
        erc20L1Address: usdcAddress,
        amount: BigNumber.from('1000000000000000000')
    });
    console.log(deposit);
}

main().catch((e) => console.error(e));
```

Can you think of any possible reasons?

**Comment by Aiyana1313** [comment]
```python

```

**Comment by ikautak** [comment]
Hi @fionnachan , thank you for your response.
First, the version of ethers I am using is 5.6.0, not 5.1.0. I've also corrected my previous post.
I tried it with node v16.20.1, but I got the same error.

```sh
$ nvm use 16
Now using node v16.20.1 (npm v8.19.4)

$ npx ts-node ./get-deposit-request.ts
ArbSdkError: No retryable data found in error
    at L1ToL2MessageGasEstimator.populateFunctionParams (/Users/oshio/src/deposit/node_modules/@arbitrum/sdk/dist/lib/message/L1ToL2MessageGasEstimator.js:189:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Erc20Bridger.getDepositRequest (/Users/oshio/src/deposit/node_modules/@arbitrum/sdk/dist/lib/assetBridger/erc20Bridger.js:303:27)
    at async main (/Users/oshio/src/deposit/get-deposit-request.ts:12:21)
Caused By: Error: no matching error (argument="sighash", value="0x08c379a0", code=INVALID_ARGUMENT, version=abi/5.7.0)
    at Logger.makeError (/Users/oshio/src/deposit/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/oshio/src/deposit/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.throwArgumentError (/Users/oshio/src/deposit/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
    at Interface.getError (/Users/oshio/src/deposit/node_modules/@ethersproject/abi/src.ts/interface.ts:267:20)
    at Interface.parseError (/Users/oshio/src/deposit/node_modules/@ethersproject/abi/src.ts/interface.ts:685:29)
    at Function.tryParseError (/Users/oshio/src/deposit/node_modules/@arbitrum/sdk/dist/lib/dataEntities/retryableData.js:57:31)
    at L1ToL2MessageGasEstimator.populateFunctionParams (/Users/oshio/src/deposit/node_modules/@arbitrum/sdk/dist/lib/message/L1ToL2MessageGasEstimator.js:178:60)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Erc20Bridger.getDepositRequest (/Users/oshio/src/deposit/node_modules/@arbitrum/sdk/dist/lib/assetBridger/erc20Bridger.js:303:27)
    at async main (/Users/oshio/src/deposit/get-deposit-request.ts:12:21) {
  inner: Error: no matching error (argument="sighash", value="0x08c379a0", code=INVALID_ARGUMENT, version=abi/5.7.0)
      at Logger.makeError (/Users/oshio/src/deposit/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (/Users/oshio/src/deposit/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at Logger.throwArgumentError (/Users/oshio/src/deposit/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
      at Interface.getError (/Users/oshio/src/deposit/node_modules/@ethersproject/abi/src.ts/interface.ts:267:20)
      at Interface.parseError (/Users/oshio/src/deposit/node_modules/@ethersproject/abi/src.ts/interface.ts:685:29)
      at Function.tryParseError (/Users/oshio/src/deposit/node_modules/@arbitrum/sdk/dist/lib/dataEntities/retryableData.js:57:31)
      at L1ToL2MessageGasEstimator.populateFunctionParams (/Users/oshio/src/deposit/node_modules/@arbitrum/sdk/dist/lib/message/L1ToL2MessageGasEstimator.js:178:60)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Erc20Bridger.getDepositRequest (/Users/oshio/src/deposit/node_modules/@arbitrum/sdk/dist/lib/assetBridger/erc20Bridger.js:303:27)
      at async main (/Users/oshio/src/deposit/get-deposit-request.ts:12:21) {
    reason: 'no matching error',
    code: 'INVALID_ARGUMENT',
    argument: 'sighash',
    value: '0x08c379a0'
  }
}
```

The tutorial also seems not to work due to the same error.
https://github.com/OffchainLabs/arbitrum-tutorials/tree/master/packages/token-deposit

In the past, the same code occasionally functioned without issues, but recently, it seems to consistently produce errors.

**Comment by ikautak** [comment]
Hi @fionnachan, I mistakenly thought that the approve transaction and deposit transaction could be sent together.

After the approve transaction was confirmed, I executed `getDepositRequest` and it worked properly!

Thank you very much.
